--- #YAML:1.0
name:                Lingua-EN-Fathom
version:             1.12
abstract:            Measure readability of English text
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Lingua::EN::Syllable:          0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Kim Ryan <kimryan at cpan org>
